version: '3.7'
services:
  nginx:
    # https://hub.docker.com/_/nginx/
    image: nginx:alpine
    ports:
        - 4200:80
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/security-headers.conf:/etc/nginx/security-headers.conf
        - ./dist/angular-ngrx-material-starter:/usr/share/nginx/html

# Run
## docker-compose up
